import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../config/theme.dart';
import '../../models/book.dart';
import '../../providers/providers.dart';

class AddBookScreen extends ConsumerStatefulWidget {
  const AddBookScreen({super.key});

  @override
  ConsumerState<AddBookScreen> createState() => _AddBookScreenState();
}

class _AddBookScreenState extends ConsumerState<AddBookScreen> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _authorController = TextEditingController();
  final _descriptionController = TextEditingController();
  final _isbnController = TextEditingController();
  BookCondition _condition = BookCondition.good;

  @override
  void dispose() {
    _titleController.dispose();
    _authorController.dispose();
    _descriptionController.dispose();
    _isbnController.dispose();
    super.dispose();
  }

  Future<void> _save() async {
    if (!_formKey.currentState!.validate()) return;

    final currentUser = ref.read(currentUserProvider);
    if (currentUser == null) return;

    final book = Book(
      id: '', // Will be generated by Supabase
      userId: currentUser.id,
      title: _titleController.text.trim(),
      author: _authorController.text.trim(),
      description: _descriptionController.text.trim().isEmpty
          ? null
          : _descriptionController.text.trim(),
      condition: _condition,
      isbn: _isbnController.text.trim().isEmpty
          ? null
          : _isbnController.text.trim(),
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    final created = await ref.read(bookActionsProvider.notifier).createBook(book);
    if (created != null && mounted) {
      ref.invalidate(myBooksProvider);
      context.pop();
    }
  }

  @override
  Widget build(BuildContext context) {
    final actionState = ref.watch(bookActionsProvider);

    return Scaffold(
      backgroundColor: AppColors.paper,
      appBar: AppBar(
        backgroundColor: AppColors.paper,
        leading: IconButton(
          icon: const Icon(Icons.close, color: AppColors.ink),
          onPressed: () => context.pop(),
        ),
        title: Text(
          'Add Book',
          style: AppTypography.serifSemiBold.copyWith(fontSize: 18, color: AppColors.ink),
        ),
        centerTitle: true,
        actions: [
          TextButton(
            onPressed: actionState.isLoading ? null : _save,
            child: Text(
              'Save',
              style: AppTypography.sansBold.copyWith(
                fontSize: 15,
                color: AppColors.rust,
              ),
            ),
          ),
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // ISBN search (simplified)
              Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: AppColors.paper2,
                  borderRadius: BorderRadius.circular(16),
                  border: Border.all(color: AppColors.line, width: 0.5),
                ),
                child: Row(
                  children: [
                    const Icon(Icons.qr_code_scanner, size: 24, color: AppColors.ink2),
                    const SizedBox(width: 12),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            'Scan ISBN barcode',
                            style: AppTypography.sansSemiBold.copyWith(
                              fontSize: 14,
                              color: AppColors.ink,
                            ),
                          ),
                          Text(
                            'Quickly fill in book details',
                            style: AppTypography.sansRegular.copyWith(
                              fontSize: 12,
                              color: AppColors.ink3,
                            ),
                          ),
                        ],
                      ),
                    ),
                    Icon(Icons.chevron_right, size: 18, color: AppColors.ink.withValues(alpha: 0.3)),
                  ],
                ),
              ),

              const SizedBox(height: 24),

              // Title
              _buildField(
                'Title',
                _titleController,
                required: true,
                hint: 'Enter book title',
              ),

              // Author
              _buildField(
                'Author',
                _authorController,
                required: true,
                hint: 'Enter author name',
              ),

              // ISBN
              _buildField(
                'ISBN (optional)',
                _isbnController,
                hint: 'Enter ISBN',
              ),

              // Condition
              _buildLabel('Condition'),
              const SizedBox(height: 8),
              Wrap(
                spacing: 8,
                runSpacing: 8,
                children: BookCondition.values.map((c) {
                  final isSelected = c == _condition;
                  return GestureDetector(
                    onTap: () => setState(() => _condition = c),
                    child: Container(
                      padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 8),
                      decoration: BoxDecoration(
                        color: isSelected ? AppColors.ink : AppColors.paper2,
                        borderRadius: BorderRadius.circular(999),
                        border: Border.all(
                          color: isSelected ? AppColors.ink : AppColors.line,
                          width: 0.5,
                        ),
                      ),
                      child: Text(
                        c.displayName,
                        style: AppTypography.sansSemiBold.copyWith(
                          fontSize: 13,
                          color: isSelected ? AppColors.paper : AppColors.ink2,
                        ),
                      ),
                    ),
                  );
                }).toList(),
              ),

              const SizedBox(height: 20),

              // Description
              _buildField(
                'Description (optional)',
                _descriptionController,
                hint: 'Describe the condition of your copy...',
                isMultiline: true,
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildLabel(String label) {
    return Text(
      label.toUpperCase(),
      style: AppTypography.sansBold.copyWith(
        fontSize: 11.5,
        letterSpacing: 0.6,
        color: AppColors.ink3,
      ),
    );
  }

  Widget _buildField(
    String label,
    TextEditingController controller, {
    bool required = false,
    String? hint,
    bool isMultiline = false,
  }) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _buildLabel(label),
          const SizedBox(height: 7),
          TextFormField(
            controller: controller,
            maxLines: isMultiline ? 4 : 1,
            decoration: InputDecoration(hintText: hint),
            validator: required
                ? (value) {
                    if (value == null || value.isEmpty) {
                      return 'This field is required';
                    }
                    return null;
                  }
                : null,
            style: isMultiline
                ? AppTypography.serifRegular.copyWith(fontSize: 15.5, color: AppColors.ink)
                : AppTypography.sansRegular.copyWith(fontSize: 15.5, color: AppColors.ink),
          ),
        ],
      ),
    );
  }
}
